routes/web.php
<?php

use App\Models\BukuTamu;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\GuruController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\BukuTamuController;
use App\Http\Controllers\Public\BukuTamuController as PublicBukuTamuController;
use App\Http\Controllers\RegisteredUserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('tamu');
})->name('index');

Route::get('create', [PublicBukuTamuController::class, 'create'])->name('tamu.create');
Route::post('store', [PublicBukuTamuController::class, 'store'])->name('tamu.store');

Route::group(['middleware' => ['auth']], function() {
    Route::get('/dashboard', function(){
        return view('dashboard');
    });
    Route::resource('roles', RoleController::class);
    Route::get('/guru/sync-telegram', [GuruController::class, 'sync_telegram'])->name('guru.sync_telegram');
    Route::resource('guru', GuruController::class);
    Route::resource('users', RegisteredUserController::class);
    Route::resource('buku-tamu', BukuTamuController::class);
    Route::get('/excel', [BukuTamuController::class, 'ekspor']);
    Route::get('/account', [RegisteredUserController::class, 'show']);
    Route::patch('/update-user', [RegisteredUserController::class, 'updateUser']);
});

require __DIR__.'/auth.php';

app/Http/Controllers/GuruController.php
<?php

namespace App\Http\Controllers;

use App\Models\m_guru;
use Illuminate\Http\Request;

class GuruController extends Controller
{
    public function __construct()
    {
        $this->middleware('permission:view_guru', ['only' => ['index', 'store']]);
        $this->middleware('permission:add_guru', ['only' => ['create', 'store']]);
        $this->middleware('permission:edit_guru', ['only' => ['edit', 'update']]);
        $this->middleware('permission:delete_guru', ['only' => ['destroy']]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $gurus = m_guru::paginate(30);
        return view('guru.index', compact('gurus'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        abort(403);
        return view('guru.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        abort(403);
        $request->validate([
            'nama' => 'required', 
            'no_telp' => 'required'
        ]);

        m_guru::create([
            'nama' => $request->nama,
            'no_telp' => $request->no_telp
        ]);

        return redirect()->route('guru.index')->with('success', 'Guru created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\m_guru  $m_guru
     * @return \Illuminate\Http\Response
     */
    public function show(m_guru $m_guru)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\m_guru  $m_guru
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = m_guru::findOrFail($id);
        return view('guru.form', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\m_guru  $m_guru
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'nama' => 'required', 
            // 'no_telp' => 'required'
        ]);

        $data = m_guru::findOrFail($id);
        $data->update($request->all());
        return redirect()->route('guru.index')->with('success', 'Guru berhasil diubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\m_guru  $m_guru
     * @return \Illuminate\Http\Response
     */
    public function destroy(m_guru $m_guru)
    {
        //
    }

    public function sync_telegram(){
        $url = 'https://api.telegram.org/bot' . config('services.telegram-bot-api.token') . '/getUpdates';

        $response = file_get_contents($url);
        $data = json_decode($response, true);

        foreach ($data['result'] as $key => $row) {
            $check = m_guru::where('id_telegram', $row['message']['from']['id'])->first();
            if (!$check) {
                m_guru::create([
                    'nama' => $row['message']['from']['first_name'] . ' ' . $row['message']['from']['last_name'],
                    'id_telegram' => $row['message']['from']['id']
                ]);
            }
        }

        return redirect()->back()->with('success', 'Berhasil di diupdate');
    }
}

resources/views/guru/form.blade.php
@extends('mylayouts.main')

@section('container')
    <div class="content-wrapper">
        <!-- Content -->

        <div class="container-xxl flex-grow-1 container-p-y">

            <div class="row">
                <form action="{{ isset($data) ? route('guru.update', $data->id) : route('guru.store') }}" method="POST">
                    @csrf
                    @isset($data)
                        @method('patch')
                    @endisset
                    <div class="col-xl-12">
                        <div class="card mb-4">
                            <h5 class="card-header">{{ isset($data) ? 'Edit' : 'Tambah' }} Guru</h5>
                            <div class="card-body">
                                <div class="mb-3 row">
                                    <div class="form-group">
                                        <label for="nama">Nama</label>
                                        <input type="text" class="mt-2 form-control @error('nama') is-invalid @enderror"
                                            id="nama" name="nama" value="{{ isset($data) ? $data->nama : old('nama') }}"
                                            placeholder="Nama">

                                        @error('nama')
                                            <div class="invalid-feedback">
                                                {{ $message }}  
                                            </div>
                                        @enderror
                                    </div>
                                    {{-- <div class="form-group">
                                        <label for="no_telp" class="mt-2">No Telepon</label>
                                        <input type="number"
                                            class="form-control mt-2 @error('no_telp') is-invalid @enderror" id="no_telp"
                                            name="no_telp" placeholder="No Telepon"
                                            value="{{ isset($data) ? $data->no_telp : old('no_telp') }}">
                                        @error('no_telp')
                                            <div class="invalid-feedback">
                                                {{ $message }}  
                                            </div>
                                        @enderror
                                    </div> --}}
                                    
                                <div class="d-flex justify-content-end mt-3">
                                    <button class="btn btn-primary" type="submit">Simpan</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/guru/index.blade.php
@extends('mylayouts.main')

@section('tambahancss')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.css">
<style>
    .swal2-container {
        z-index: 9999 !important;
    }

    .dropdown-toggle::after {
        display: none;
    }
</style>
@endsection

@section('container')

<div class="content-wrapper">
    <!-- Content -->

    <div class="container-xxl flex-grow-1 container-p-y">

        <div class="card">
            <div class="container-fluid p-0">
                <div class="row">
                    <div class="col-md-7">
                        <h5 class="card-header">Guru</h5>
                    </div>
                    <div class="col-md d-flex justify-content-end align-items-center" style="padding-right: 2rem;">
                        <a href="{{ route('guru.sync_telegram') }}" class="btn btn-primary"
                            style="margin-right: 10px">Sync Telegram</a>
                        {{-- <a href="{{ route('guru.create') }}" class="btn btn-primary tombol-buat-user"
                            style="margin-right: 10px">Tambah</a> --}}
                    </div>
                </div>
            </div>
            <div class="container" style="overflow: auto;min-height: 65vh">
                <div class="table-responsive">
                    <table class="table-hover table text-center">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Nama</th>
                                {{-- <th>NO WA</th> --}}
                                @can('edit_guru', 'delete_guru')
                                <th>Actions</th>
                                @endcan
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($gurus as $guru)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $guru->nama }}</td>
                                {{-- <td>{{ $guru->no_telp }}</td> --}}
                                @can('edit_guru', 'delete_guru')
                                <td>
                                    @can('edit_guru')
                                    <a href="{{ route('guru.edit', $guru->id) }}"
                                        class="btn btn-warning">Update</a>
                                    @endcan
                                    @can('delete_guru')
                                    <form action="{{ route('guru.destroy', $guru->id) }}" method="post"
                                        class="d-inline" id="delete{{ $guru->id }}">
                                        @csrf
                                        @method('delete')
                                        <button type="button" class="btn btn-danger swal-confrim">Hapus</button>
                                    </form>
                                    @endcan
                                </td>
                                @endcan
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>
    <!-- / Content -->
    <!-- Modal -->

    <div class="content-backdrop fade"></div>
</div>
@endsection

@section('tambahanjs')
<script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js"></script>
<script>
    $(".swal-confrim").click(function(e) {
            id = e.target.dataset.id;
            Swal.fire({
                title: 'Apakah anda yakin ingin hapus data ini?',
                text: "Data yang terhapus tidak dapat dikembalikan",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'

            }).then((result) => {
                if (result.isConfirmed) {
                    $(`#delete${id}`).submit();
                } else {

                }

            })

        });
</script>

<script>
    const alertNontifikasi = document.querySelector('.alert-nontifikasi');
        const myTimeout = setTimeout(myGreeting, 5000);

        function myGreeting() {
            if (alertNontifikasi) {
                alertNontifikasi.style.display = 'none';
            }
        }
</script>
@endsection