routes/web.php
<?php

use App\Models\BukuTamu;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\GuruController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\BukuTamuController;
use App\Http\Controllers\Public\BukuTamuController as PublicBukuTamuController;
use App\Http\Controllers\RegisteredUserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('tamu');
})->name('index');

Route::get('create', [PublicBukuTamuController::class, 'create'])->name('tamu.create');
Route::post('store', [PublicBukuTamuController::class, 'store'])->name('tamu.store');

Route::group(['middleware' => ['auth']], function() {
    Route::get('/dashboard', function(){
        return view('dashboard');
    });
    Route::resource('roles', RoleController::class);
    Route::get('/guru/sync-telegram', [GuruController::class, 'sync_telegram'])->name('guru.sync_telegram');
    Route::resource('guru', GuruController::class);
    Route::resource('users', RegisteredUserController::class);
    Route::resource('buku-tamu', BukuTamuController::class);
    Route::get('/excel', [BukuTamuController::class, 'ekspor']);
    Route::get('/account', [RegisteredUserController::class, 'show']);
    Route::patch('/update-user', [RegisteredUserController::class, 'updateUser']);
});

require __DIR__.'/auth.php';

resources/views/mypartials/aside.blade.php
<aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">
    <div class="app-brand demo">
        <a href="/dashboard" class="app-brand-link">
            <span class="app-brand-logo demo">
                <img src="/img/logoStarbhakForApp.png" alt="" style="width: 2.8rem;">
            </span>
            <span class="app-brand-text demo menu-text fw-bolder ms-2" style="text-transform: capitalize;">Buku
                Tamu</span>
        </a>

        <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none">
            <i class="bx bx-chevron-left bx-sm align-middle"></i>
        </a>
    </div>

    <div class="menu-inner-shadow"></div>

    <ul class="menu-inner py-1" style="overflow-y: auto;overflow-x: hidden">
        <!-- Dashboard -->
        <li class="menu-item {{ Request::is('dashboard') ? 'active' : '' }}">
            <a href="/dashboard" class="menu-link">
                <i class="menu-icon tf-icons bx bx-home-circle"></i>
                <div data-i18n="Analytics">Dashboard</div>
            </a>
        </li>

        @can('view_roles', 'add_roles', 'edit_roles', 'delete_roles')
            {{-- Roles --}}
            <li class="menu-item {{ Request::is('roles*') ? 'active' : '' }}">
                <a href="{{ route('roles.index') }}" class="menu-link">
                    <i class="menu-icon tf-icons bx bx-lock-open-alt"></i>
                    <div data-i18n="Analytics">Roles</div>
                </a>
            </li>
        @endcan

        @can('view_users', 'add_users', 'edit_users', 'delete_users')
            <!-- Users -->
            <li class="menu-item {{ Request::is('users*') ? 'active' : '' }}">
                <a href="{{ route('users.index') }}" class="menu-link">
                    <i class="menu-icon tf-icons bx bx-user"></i>
                    <div data-i18n="Analytics">Users</div>
                </a>
            </li>
        @endcan

        @can('view_guru', 'add_guru', 'edit_guru', 'delete_guru')
            <li class="menu-item {{ Request::is('guru*') ? 'active' : '' }}">
                <a href="{{ route('guru.index') }}" class="menu-link">
                    <i class="menu-icon tf-icons bx bx-user"></i>
                    <div data-i18n="Analytics">Data Guru</div>
                </a>
            </li>
        @endcan

        @can('view_buku_tamu', 'add_buku_tamu', 'edit_buku_tamu', 'delete_buku_tamu', 'buku_tamu_ekspor')
            <li class="menu-item {{ Request::is('buku-tamu*') ? 'active' : '' }}">
                <a href="{{ route('buku-tamu.index') }}" class="menu-link">
                    <i class='menu-icon tf-icons bx bx-book'></i>
                    <div data-i18n="Analytics">Buku Tamu</div>
                </a>
            </li>
        @endcan

    </ul>
</aside>

resources/views/mypartials/navbar.blade.php
<nav class="layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme"
    id="layout-navbar">
    <div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none">
        <a class="nav-item nav-link px-0 me-xl-4" href="javascript:void(0)">
            <i class="bx bx-menu bx-sm"></i>
        </a>
    </div>

    <div class="navbar-nav-right d-flex align-items-center" id="navbar-collapse">
        <!-- Search -->
        <form action="/buku-tamu" method="get">
            <div class="navbar-nav align-items-center">
                <div class="nav-item d-flex align-items-center">
                    <button type="submit" style="background: transparent;border: none;"><i class="bx bx-search fs-4 lh-0"></i></button>
                    <input type="text" class="form-control border-0 shadow-none"
                        placeholder="Search Nama , Instansi" name="search"
                        value="{{ request('search') }}" />
                </div>
            </div>
        </form>
        <!-- /Search -->

        <ul class="navbar-nav flex-row align-items-center ms-auto">
            <li class="nav-item navbar-dropdown dropdown-user dropdown">
                <a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);" data-bs-toggle="dropdown">
                    <div class="avatar avatar-online">
                        @if (Auth::user()->foto_profil == '/img/avatar-1.png')
                            <img src="{{ Auth::user()->foto_profil }}" alt class="w-px-40 h-auto rounded-circle" />
                        @else
                            <img src="{{ asset('storage/' . Auth::user()->foto_profil) }}" alt
                                class="w-px-40 rounded-circle" style="width: 100% !important;"/>
                        @endif
                    </div>
                </a>
                <ul class="dropdown-menu dropdown-menu-end">
                    <li>
                        <a class="dropdown-item" href="#">
                            <div class="d-flex">
                                <div class="flex-shrink-0 me-3">
                                    <div class="avatar avatar-online">
                                        @if (Auth::user()->foto_profil == '/img/avatar-1.png')
                                            <img src="{{ Auth::user()->foto_profil }}" alt
                                                class="w-px-40 h-auto rounded-circle" />
                                        @else
                                            <img src="{{ asset('storage/' . Auth::user()->foto_profil) }}" alt
                                                class="w-px-40 rounded-circle" style="width: 100% !important;" />
                                        @endif
                                    </div>
                                </div>
                                <div class="flex-grow-1">
                                    <span class="fw-semibold d-block"
                                        style="text-transform: capitalize;">{{ auth()->user()->name }}</span>
                                    <small class="text-muted">Admin</small>
                                </div>
                            </div>
                        </a>
                    </li>
                    <li>
                        <div class="dropdown-divider"></div>
                    </li>
                    <li>
                        <a class="dropdown-item" href="/account">
                            <i class="bx bx-user me-2"></i>
                            <span class="align-middle">My Profile</span>
                        </a>
                    </li>
                    <li>
                        <div class="dropdown-divider"></div>
                    </li>
                    <li>
                        <form method="POST" action="{{ route('logout') }}">
                            @csrf
                            <button class="dropdown-item"><i class="bx bx-power-off me-2"></i> Log Out</button>
                        </form>
                    </li>
                </ul>
            </li>
            <!--/ User -->
        </ul>
    </div>
</nav>