routes/web.php
<?php

use App\Models\BukuTamu;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\GuruController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\BukuTamuController;
use App\Http\Controllers\Public\BukuTamuController as PublicBukuTamuController;
use App\Http\Controllers\RegisteredUserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('tamu');
})->name('index');

Route::get('create', [PublicBukuTamuController::class, 'create'])->name('tamu.create');
Route::post('store', [PublicBukuTamuController::class, 'store'])->name('tamu.store');

Route::group(['middleware' => ['auth']], function() {
    Route::get('/dashboard', function(){
        return view('dashboard');
    });
    Route::resource('roles', RoleController::class);
    Route::get('/guru/sync-telegram', [GuruController::class, 'sync_telegram'])->name('guru.sync_telegram');
    Route::resource('guru', GuruController::class);
    Route::resource('users', RegisteredUserController::class);
    Route::resource('buku-tamu', BukuTamuController::class);
    Route::get('/excel', [BukuTamuController::class, 'ekspor']);
    Route::get('/account', [RegisteredUserController::class, 'show']);
    Route::patch('/update-user', [RegisteredUserController::class, 'updateUser']);
});

require __DIR__.'/auth.php';

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use DB;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class RoleController extends Controller
{

    public function __construct()
    {
        $this->middleware('permission:view_roles|add_roles|edit_roles|delete_roles', ['only' => ['index', 'store']]);
        $this->middleware('permission:add_roles', ['only' => ['create', 'store']]);
        $this->middleware('permission:edit_roles', ['only' => ['edit', 'update']]);
        $this->middleware('permission:delete_roles', ['only' => ['destroy']]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $roles = Role::all();
        $rolePermissions = [];

        foreach ($roles as $role) {
            $rolePermissions[] = Permission::join("role_has_permissions", "role_has_permissions.permission_id", "=", "permissions.id")
                ->where("role_has_permissions.role_id", $role->id)
                ->get();
        }

        $permissions = Permission::get();
        return view('roles.index', compact('roles', 'permissions', 'rolePermissions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'name' => 'required|unique:roles,name',
            'permission' => 'required',
        ]);

        $validatedData['name'] = strtolower(str_replace(" ", "_", $request->name));

        $role = Role::create($validatedData);
        $role->syncPermissions($request->permission);

        return redirect()->route('roles.index')
            ->with('success', 'Role created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $role = Role::find($id);
        $permissions = Permission::get();
        $rolePermissions = DB::table("role_has_permissions")->where("role_has_permissions.role_id", $id)
            ->pluck('role_has_permissions.permission_id', 'role_has_permissions.permission_id')
            ->all();

        return view('roles.update', compact('role', 'permissions', 'rolePermissions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validatedData = $request->validate([
            'name' => 'required',
            'permission' => 'required',
        ]);

        $role = Role::find($id);
        //? kenapa tidak pakai update karena yang kita ubah hanya nama rolenya saja, dan untuk coloum yang lain seperti guard_name kan tidak ada berarti jika tidak ada nanti ketika di update akan error
        $role->name = strtolower(str_replace(" ", "_", $request->name));
        $role->save();

        $role->syncPermissions($request->permission);

        return redirect()->route('roles.index')
            ->with('success', 'Role updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $users = User::with('roles')->get();
        $role = Role::find($id);

        foreach ($users as $key => $user) {
            if ($user->hasRole($role->name)) {
                $user->delete();
            }
        }

        $role->delete();

        return redirect()->route('roles.index')
            ->with('success', 'Role deleted successfully');
    }
}

resources/views/roles/index.blade.php
@extends('mylayouts.main')

@section('tambahancss')
    <style>
        .swal2-container {
            z-index: 9999 !important;
        }
    </style>
@endsection

@section('container')

    <div class="content-wrapper">
        <!-- Content -->

        <div class="container-xxl flex-grow-1 container-p-y">

            <div class="card">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-10">
                            <h5 class="card-header">Roles</h5>
                        </div>
                        <div class="col-md-2 d-flex justify-center align-items-center">
                            @can('add_roles')
                                <button type="button" class="btn btn-primary tombol-buat-user" data-bs-toggle="modal"
                                    data-bs-target="#exampleModal">
                                    Create Role
                                </button>
                            @endcan
                        </div>
                    </div>
                </div>
                <div class="container" style="height: 65vh;overflow: auto;">
                    <div id="accordionIcon" class="accordion mt-3 accordion-without-arrow">
                        @foreach ($roles as $key => $role)
                            <div class="accordion-item card mb-3">
                                <h2 class="accordion-header text-body d-flex justify-content-between" id="accordionIconOne">
                                    <button type="button" class="accordion-button collapsed" data-bs-toggle="collapse"
                                        data-bs-target="#accordionIcon-{{ $loop->iteration }}"
                                        aria-controls="accordionIcon-{{ $loop->iteration }}" style="text-transform: capitalize;">
                                        {{ $loop->iteration }}. Role {{ str_replace("_", " ", $role->name) }}
                                        <i class='bx bx-chevron-right' style="position: absolute;right: 1rem;font-size: 1.7rem;"></i> 
                                    </button>
                                </h2>

                                <div id="accordionIcon-{{ $loop->iteration }}" class="accordion-collapse collapse"
                                    data-bs-parent="#accordionIcon">
                                    <div class="accordion-body">
                                        <div class="container-fluid">
                                            <div class="row">
                                                <div class="col-md-8">
                                                    <h5 class="card-header ps-0" style="text-transform: capitalize;">Hak akses untuk role {{ str_replace("_", " ", $role->name) }}
                                                    </h5>
                                                </div>
                                                <div class="col d-flex justify-content-center align-items-center">
                                                    @can('edit_roles')
                                                        @if ($role->name == 'admin')
                                                            <a href="{{ route('roles.edit', $role->id) }}"
                                                                class="btn btn-warning disabled"
                                                                style="margin-right: 10px;">Update</a>
                                                        @else
                                                            <a href="{{ route('roles.edit', $role->id) }}"
                                                                class="btn btn-warning" style="margin-right: 10px;">Update</a>
                                                        @endif
                                                    @endcan
                                                    @can('edit_roles')
                                                        @if ($role->name == 'admin')
                                                            <form action="{{ route('roles.destroy', $role->id) }}"
                                                                method="post" id="delete{{ $role->id }}">
                                                                @csrf
                                                                @method('delete')
                                                                <a href="#" data-id={{ $role->id }}
                                                                    class="btn btn-danger swal-confrim disabled">
                                                                    Hapus
                                                                </a>
                                                            </form>
                                                        @else
                                                            <form action="{{ route('roles.destroy', $role->id) }}"
                                                                method="post" id="delete{{ $role->id }}">
                                                                @csrf
                                                                @method('delete')
                                                                <a href="#" data-id={{ $role->id }}
                                                                    class="btn btn-danger swal-confrim">
                                                                    Hapus
                                                                </a>
                                                            </form>
                                                        @endif
                                                    @endcan
                                                </div>
                                            </div>
                                        </div>
                                        {{-- <p>{{ $rolePermission->name }}</p> --}}
                                        <div class="container-fluid">
                                            <div class="row flex-wrap">
                                                @foreach ($rolePermissions[$key] as $rolePermission)
                                                    <div class="col-md-3 mb-2 mt-2">
                                                        {{ str_replace('_', ' ', $rolePermission->name) }}</div>
                                                @endforeach
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        @endforeach

                    </div>
                </div>
            </div>

        </div>
        <!-- / Content -->
        <!-- Modal -->

        @can('add_roles')
            <div class="modalkey modal fade @error('name') show @enderror @error('email') show @enderror @error('password') show @enderror"
                id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true"
                @error('name') style="display: block;background: rgba(69,90,100, .5);" @enderror
                @error('email') style="display: block;background: rgba(69,90,100, .5);" @enderror
                @error('password') style="display: block;background: rgba(69,90,100, .5);" @enderror>
                <div class="modal-dialog">
                    <div class="modal-content">
                        <form action="{{ route('roles.store') }}" method="post">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Create Role</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                @csrf
                                <div class="mb-3 row">
                                    <label for="html5-text-input" class="col-md-3 col-form-label">Name Role</label>
                                    <div class="col-md-9">
                                        <input class="form-control @error('name') is-invalid @enderror" type="text"
                                            id="html5-text-input" placeholder="Name Role" name="name"
                                            value="{{ old('name') }}" />
                                        @error('name')
                                            <div class="invalid-feedback d-block">
                                                {{ $message }}
                                            </div>
                                        @enderror
                                    </div>
                                </div>
                                @foreach ($permissions as $permission)
                                    <div class="form-check mt-3">
                                        <input class="form-check-input" type="checkbox" value="{{ $permission->id }}"
                                            id="{{ $permission->name }}" name="permission[]" />
                                        <label class="form-check-label"
                                            for="{{ $permission->name }}">{{ $permission->name }}</label>
                                    </div>
                                @endforeach
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary tombol-close-bawah"
                                    data-bs-dismiss="modal">Close</button>
                                <button type="submit" class="btn btn-primary">Create Role</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        @endcan

        <div class="content-backdrop fade"></div>
    </div>
@endsection

@section('tambahanjs')
    <script>
        const modal = document.querySelector('.modalkey');
        const btnClose = document.querySelector('.btn-close');
        const tombolCloseBawah = document.querySelector('.tombol-close-bawah');

        btnClose.addEventListener('click', function() {
            modal.classList.remove('show');
            modal.style.display = 'none';
            modal.style.background = 'none';
        })

        tombolCloseBawah.addEventListener('click', function() {
            modal.classList.remove('show');
            modal.style.display = 'none';
            modal.style.background = 'none';
        })
    </script>
    <script>
        $(".swal-confrim").click(function(e) {
            id = e.target.dataset.id;
            Swal.fire({
                title: 'Apakah anda yakin ingin hapus role ini?',
                text: "Data yang terhapus tidak dapat dikembalikan",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'

            }).then((result) => {
                if (result.isConfirmed) {
                    $(`#delete${id}`).submit();
                } else {

                }

            })

        });
    </script>
@endsection

resources/views/roles/update.blade.php
@extends('mylayouts.main')

@section('container')
    <div class="content-wrapper">
        <!-- Content -->

        <div class="container-xxl flex-grow-1 container-p-y">

            <div class="row">
                <form action="{{ route('roles.update', $role->id) }}" method="POST">
                    @csrf
                    @method('patch')
                    <div class="col-xl-12">
                        <div class="card mb-4">
                            <h5 class="card-header">Ubah Role</h5>
                            <div class="card-body">
                                <div class="mb-3 row">
                                    <label for="html5-text-input" class="col-md-2 col-form-label">Name Role</label>
                                    <div class="col-md-10">
                                        <input style="text-transform: capitalize;" class="form-control @error('name') is-invalid @enderror" type="text"
                                            value="{{ str_replace("_", " ", $role->name), old('name') }}" id="html5-text-input"
                                            placeholder="Name Role" name="name"  />
                                        @error('name')
                                            <div class="invalid-feedback d-block">
                                                {{ $message }}
                                            </div>
                                        @enderror
                                    </div>
                                </div>
                                @foreach ($permissions as $permission)
                                    @if (in_array($permission->id, $rolePermissions))
                                        <div class="form-check mt-3">
                                            <input class="form-check-input" type="checkbox" value="{{ $permission->id }}"
                                                id="{{ $permission->name }}" name="permission[]" checked/>
                                            <label class="form-check-label"
                                                for="{{ $permission->name }}">{{ $permission->name }}</label>
                                        </div>
                                    @else
                                        <div class="form-check mt-3">
                                            <input class="form-check-input" type="checkbox" value="{{ $permission->id }}"
                                                id="{{ $permission->name }}" name="permission[]" />
                                            <label class="form-check-label"
                                                for="{{ $permission->name }}">{{ $permission->name }}</label>
                                        </div>
                                    @endif
                                @endforeach
                                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                                    <button class="btn btn-primary" type="submit">Simpan Perubahan</button>
                                </div>
                            </div>
                        </div>

                    </div>
                </form>
            </div>
        </div>
        <!-- / Content -->

        <div class="content-backdrop fade"></div>
    </div>
@endsection